CREATE TABLE users(
    ID VARCHAR PRIMARY KEY,
    IMAGE VARCHAR,
    IS_LOCKED BOOLEAN,
    LOGIN VARCHAR UNIQUE,
    NAME VARCHAR,
    PASSWORD VARCHAR,
    ROLE SMALLINT
)

CREATE TABLE company(
    ID VARCHAR PRIMARY KEY,
    CNPJ VARCHAR(14) UNIQUE,
    COMPANY_ADRESS VARCHAR,
    COMPANY_NAME VARCHAR,
    COMPANY_ROLE VARCHAR,
    HAS_DELIVERY BOOLEAN,
    LOGO VARCHAR,
    WORK_TIME VARCHAR,
    ID_USER VARCHAR REFERENCES users(ID)
)

CREATE TABLE product(
    ID VARCHAR PRIMARY KEY,
    PRICE REAL,
    PRODUCT_IMAGE VARCHAR,
    PRODUCT_NAME VARCHAR,
    PRODUCT_QTD INTEGER,
    PRODUCT_TYPE VARCHAR,
    ID_COMPANY VARCHAR REFERENCES company(ID)
)